<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Y.K_RBQ' shared service.

return $this->privates['.service_locator.Y.K_RBQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'category' => ['privates', '.errored..service_locator.Y.K_RBQ.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.Y.K_RBQ": it references class "App\\Entity\\Category" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
], [
    'category' => 'App\\Entity\\Category',
    'manager' => '?',
]);
