<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IgCayIA' shared service.

return $this->privates['.service_locator.IgCayIA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'stats' => ['privates', 'App\\Service\\Stats', 'getStatsService.php', true],
], [
    'manager' => '?',
    'stats' => 'App\\Service\\Stats',
]);
