<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.prwlndz' shared service.

return $this->privates['.service_locator.prwlndz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'product' => ['privates', '.errored..service_locator.prwlndz.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.prwlndz": it references class "App\\Entity\\Product" but no such service exists.'],
], [
    'manager' => '?',
    'product' => 'App\\Entity\\Product',
]);
