<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.34un6EX' shared service.

return $this->privates['.service_locator.34un6EX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'comment' => ['privates', '.errored..service_locator.34un6EX.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.34un6EX": it references class "App\\Entity\\Comment" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
], [
    'comment' => 'App\\Entity\\Comment',
    'manager' => '?',
]);
