<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxCx2Bm\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxCx2Bm/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLxCx2Bm.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLxCx2Bm\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLxCx2Bm\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LxCx2Bm',
    'container.build_id' => '4459a223',
    'container.build_time' => 1584990629,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxCx2Bm');
